name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "utterblue.us.kg"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "utterblue.us.kg"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.utterblue.us.kg", custom_domain = true },
#   { pattern = "quay.utterblue.us.kg", custom_domain = true },
#   { pattern = "gcr.utterblue.us.kg", custom_domain = true },
#   { pattern = "k8s-gcr.utterblue.us.kg", custom_domain = true },
#   { pattern = "k8s.utterblue.us.kg", custom_domain = true },
#   { pattern = "ghcr.utterblue.us.kg", custom_domain = true },
#   { pattern = "cloudsmith.utterblue.us.kg", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.utterblue.us.kg", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
